force-app/main/default/objects/Royalty_Request__c.object
<CustomObject>
    <fields>
        <fullName>ASTM_Product_Setup_Required__c</fullName>
        <label>ASTM Product Setup Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_City__c</fullName>
        <label>Account City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Postal_Code__c</fullName>
        <label>Account Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_State__c</fullName>
        <label>Account State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NM</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Street__c</fullName>
        <label>Account Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Requests</relationshipLabel>
        <relationshipName>Royalty_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>ASTM Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Counter_Subscription__c</fullName>
        <inlineHelpText>Description for user</inlineHelpText>
        <label>Counter Subscription</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DRM_On_or_Off__c</fullName>
        <label>DRM On or Off</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Mechanism__c</fullName>
        <label>Delivery Mechanism</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ASTM Compass</fullName>
                </value>
                <value>
                    <fullName>Own Platform</fullName>
                </value>
                <value>
                    <fullName>Books</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Number_of_Users__c</fullName>
        <label>Estimated Number of Users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Existing_Revenue__c</fullName>
        <label>Existing Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Forced_Login__c</fullName>
        <label>Forced Login</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IP_Address_Type__c</fullName>
        <label>Access Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Username/Password</fullName>
                </value>
                <value>
                    <fullName>Applet</fullName>
                </value>
                <value>
                    <fullName>IP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IP_Addresses__c</fullName>
        <label>IP Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Misc_Comments__c</fullName>
        <label>Reseller Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Locations__c</fullName>
        <label>Number of Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <label>Opportunity Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Loss</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Request</label>
        <referenceTo>Royalty_Request__c</referenceTo>
        <relationshipLabel>Royalty Requests</relationshipLabel>
        <relationshipName>Royalty_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Mix__c</fullName>
        <label>Product Mix</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Custom Collections</fullName>
                </value>
                <value>
                    <fullName>Add&apos;l Site Added to Existing Account</fullName>
                </value>
                <value>
                    <fullName>All DL Journals</fullName>
                </value>
                <value>
                    <fullName>DL Complete</fullName>
                </value>
                <value>
                    <fullName>BOS Compass Custom</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 1</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 2</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 3</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 4</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 5</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 6</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 7</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 8</fullName>
                </value>
                <value>
                    <fullName>BOS Section 1 Volume 9</fullName>
                </value>
                <value>
                    <fullName>BOS Section 10 Volume 1</fullName>
                </value>
                <value>
                    <fullName>BOS Section 10 Volume 2</fullName>
                </value>
                <value>
                    <fullName>BOS Section 10 Volume 3</fullName>
                </value>
                <value>
                    <fullName>BOS Section 10 Volume 4</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 1</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 2</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 3</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 4</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 5</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 6</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 7</fullName>
                </value>
                <value>
                    <fullName>BOS Section 11 Volume 8</fullName>
                </value>
                <value>
                    <fullName>BOS Section 12 Volume 1</fullName>
                </value>
                <value>
                    <fullName>BOS Section 12 Volume 2</fullName>
                </value>
                <value>
                    <fullName>BOS Section 13 Volume 1</fullName>
                </value>
                <value>
                    <fullName>BOS Section 13 Volume 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response_Due_Date__c</fullName>
        <label>Response Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Royalty_Amount__c</fullName>
        <label>Royalty Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Royalty_Expiration_Date__c</fullName>
        <label>Royalty Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Usage_Reports_Hidden__c</fullName>
        <label>Usage Reports Hidden</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Watermark__c</fullName>
        <label>Watermark</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Royalty Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>Royalty Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RRFormController.cls
public with sharing class RRFormController {

	public Royalty_Request__c r_request = new Royalty_Request__c();
	public Royalty_Request__c getR_Request(){
		r_request = [SELECT Id, Name, Account__r.Name, Response_Due_Date__c, 
		Approval_Status__c, Opportunity_Status__c, Comments__c, Delivery_Mechanism__c, ASTM_Product_Setup_Required__c,
		IP_Address_Type__c, URL__c, IP_Addresses__c, Parent_Request__r.Name, DRM_On_or_Off__c, Forced_Login__c,
		Watermark__c, Usage_Reports_Hidden__c, Counter_Subscription__c, Royalty_Amount__c, Royalty_Expiration_Date__c,
		Existing_Revenue__c, Number_of_Locations__c, Product_Mix__c, Estimated_Number_of_Users__c, Misc_Comments__c,
		Contract_Start_Date__c, Contract_End_Date__c, Account_Street__c, Account_City__c,
		Account_State__c, Account_Postal_Code__c, Account_Country__c from Royalty_Request__c where Id = :System.currentPageReference().getParameters().get('Id')];
		return r_request;
	}

	public PageReference createRR(){ 
        Id rid =getR_Request().Id;
        
        Attachment att = new Attachment(name = 'resellerorder.xls');
        PageReference RR_page = new PageReference('/apex/RRFormPage_new');
        RR_page .getParameters().put('id',getR_Request().Id);
        // return page content as blob type
        //att.body = PO_page .getContentAsPDF();
        //tested below to create .doc, need to change file name ext. too
        Blob content;
		if (Test.IsRunningTest()){
		content=Blob.valueOf('UNIT.TEST');
		} else {
        content= RR_page .getContent();
   		}
        att.body = content;
        att.ContentType = 'application/xls';
        //att.body = Order_page .getContent();
        // Associate with project's record Id
        att.parentid = getR_Request().Id;
        insert att;
    
        PageReference callPage = new PageReference('/'+rid);
        return callPage;  
    }
}