force-app/main/default/objects/Royalty_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Royalty Requests</relationshipLabel>
        <relationshipName>Royalty_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>Used in Trigger when set will get auto updated by scheduled class when royalty payments generated.</description>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annually</fullName>
                    <default>true</default>
                    <label>Annually</label>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Royalty_Amount__c</fullName>
        <label>Royalty Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Royalty Request</label>
    <nameField>
        <displayFormat>Req-{0000}</displayFormat>
        <label>Royalty Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Royalty Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RoyaltyPaymentTest.cls
/**
 * Created by William McCullough from OpenGate Consulting on 3/2/2020.
 */

@IsTest
private class RoyaltyPaymentTest {
    @IsTest
    static void testRoyaltyPaymentSchedulerMethods() {
        Test.startTest();
        //Remove scheduled job
        RoyaltyPaymentSchedulable.RemoveSchedulerMethod();

        // validate the schedule removed
        List<CronTrigger> remove = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE '%RoyaltyPayments4Quarters%'];
        System.assertEquals(0, remove.size());

        RoyaltyPaymentSchedulable.SchedulerMethod();
        // validate the schedule added
        List<CronTrigger> job = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE '%RoyaltyPayments4Quarters%'];
        System.assertEquals(1, job.size());
        Test.stopTest();
    }
    @IsTest
    static void testRoyaltyPaymentCreation() {
        Account ca = new Account(Name = 'testaccount', Oracle_Account_Number__c = '111222333', BillingCountryCode = 'US');
        insert ca;
        Royalty_Request__c royaltyRequest1 = new Royalty_Request__c(
                Account__c = ca.Id,
                Royalty_Amount__c = 150,
                Approval_Status__c = 'Approved',
                Approval_Date__c = Date.today(),
                Payment_Frequency__c = 'Annually',
                Payment_Date__c = Date.today()
        );
        insert royaltyRequest1;
        Royalty_Request__c royaltyRequest2 = new Royalty_Request__c(
                Account__c = ca.Id,
                Royalty_Amount__c = 350,
                Approval_Status__c = 'Approved',
                Approval_Date__c = Date.today(),
                Payment_Frequency__c = 'Quarterly',
                Payment_Date__c = Date.today()
        );
        insert royaltyRequest2;
        Royalty_Request__c royaltyRequest3 = new Royalty_Request__c(
                Account__c = ca.Id,
                Royalty_Amount__c = 250,
                Approval_Status__c = 'Approved',
                Approval_Date__c = Date.today(),
                Payment_Frequency__c = 'Monthly',
                Payment_Date__c = Date.today()
        );
        insert royaltyRequest3;
        Test.startTest();
        RoyaltyPaymentActions.createPaymentsFromRequests();
        Test.stopTest();
    }
}